// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzwe_GD-U-udb0BKW70it-WBIabDw5vI4',
    appId: '1:445312139082:web:1fc00afd025e39e2688bb3',
    messagingSenderId: '445312139082',
    projectId: 'homescout-10855',
    authDomain: 'homescout-10855.firebaseapp.com',
    storageBucket: 'homescout-10855.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_H1Ae3mCVvzMkPZNe41wP3s_IoeFzrkg',
    appId: '1:445312139082:android:71df633ec0e3b4fe688bb3',
    messagingSenderId: '445312139082',
    projectId: 'homescout-10855',
    storageBucket: 'homescout-10855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxSoinlA4k6QtYo2fPQVG0fdqHCvps6L4',
    appId: '1:445312139082:ios:ec5361f4b8223b79688bb3',
    messagingSenderId: '445312139082',
    projectId: 'homescout-10855',
    storageBucket: 'homescout-10855.appspot.com',
    iosBundleId: 'com.example.homescout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxSoinlA4k6QtYo2fPQVG0fdqHCvps6L4',
    appId: '1:445312139082:ios:ec5361f4b8223b79688bb3',
    messagingSenderId: '445312139082',
    projectId: 'homescout-10855',
    storageBucket: 'homescout-10855.appspot.com',
    iosBundleId: 'com.example.homescout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzwe_GD-U-udb0BKW70it-WBIabDw5vI4',
    appId: '1:445312139082:web:84fd687213919a69688bb3',
    messagingSenderId: '445312139082',
    projectId: 'homescout-10855',
    authDomain: 'homescout-10855.firebaseapp.com',
    storageBucket: 'homescout-10855.appspot.com',
  );

}